spring.application.name=network-security-monitor
spring.datasource.url=jdbc:sqlite:../alerts.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect